services:
  - type: web
    name: spotnshop-app
    runtime: docker
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: spotnshop-db
          property: connectionString
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: spotnshop-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: spotnshop-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: spotnshop-db
          property: password

databases:
  - name: spotnshop-db
    databaseName: spotnshop
    user: spotnshop_user
    plan: free